### ISSUE TITLE
hey 

### ISSUE THREAD

**Issue by GrammyLi** [KrutikGadhiya/Sign-language-detection-using-open-cv#1]
The code is too confusing. Don't know where to start

**Comment by KrutikGadhiya** [comment]
GUI.py is the main file, sorry for the bad structure of code and naming conventions for files, as this was my first project, i was learning and just doing things.

**Comment by KrutikGadhiya** [comment]
the harrcascade folder has the trained files, that were trained using the GUI harrcascade trainer (https://amin-ahmadi.com/cascade-trainer-gui/)
